### ISSUE TITLE
allow.json에 삼립, 파리크라상, 비알코리아 바코드 대역 추가

### ISSUE THREAD

**Issue by lego37yoon** [saengwon-kim/isspc#4]
안녕하세요, 이번에 [한겨레](https://m.hani.co.kr/arti/society/society_general/1064315.html) 기사로 같이 언급된 예스피씨 개발자 종이상자입니다.

혹시 allow.json 파일에 8801068 대역 외에

- 880939312 혹은 8804007 (SPC 삼립 및 삼립 대역)
- 880928863 (비알코리아 대역)
- 880969023 (파리크라상 대역)

을 추가하실 계획이 있으신가요? 아무래도 기사에는 제가 적용한 대역에 대한 설명이 구분 없이 작성되어있기도 하고, 상호 유사한 서비스를 만드는 입장에서 서로 보완되면 좋을 것 같아 이슈 남겨봅니다.

감사합니다.

**Comment by saengwon-kim** [comment]
안녕하세요, 기사를 보고 저도 종이상자님의 프로젝트를 확인하였었는데 이렇게 연락주셔서 감사합니다!  
같은 서비스를 운영하시는 분을 뵙게 되어 반갑습니다.

제안해주신 대역을 모두 확인하여 본 repo에 추가하려 합니다. 안그래도 사용자분들께서 호빵, 베스킨라빈스 음료 등으로 해당 대역에 속하는 오류들을 제보해주셔서 DB에 추가하고 있었는데 이렇게 대역을 알려주시니 훨씬 간단하게 정리할 수 있을 것 같습니다.

큰 도움이 되는 정보를 공유해주셔서 정말 감사합니다.
